[package]
name = "lorawan-sniffer"
version = "0.1.0"
authors = ["lthiery <me@louisthiery.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3"
lorawan = { git = "https://github.com/ivajloip/rust-lorawan"}
semtech-udp = { git = "https://github.com/lthiery/semtech-udp"}
base64 = "0.12.0"
mio = "0.6"
