[package]
name = "lorawan-sniffer"
version = "0.1.0"
authors = ["lthiery <me@louisthiery.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3.2", default-features = false }
arrayref = "0.3"
#lorawan = { git = "https://github.com/ivajloip/rust-lorawan"}
semtech-udp = { git = "https://github.com/lthiery/semtech-udp"}
lorawan = { path = "../rust-lorawan"}
base64 = "0.12.0"
mio = "0.6"
aes = "0.3.2"
openssl = "0.10.28"